# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr = np.zeros(10)
print(arr)
print(arr.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))

[5 7 9]


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
arr = np.arange(10, 50)
reverse_arr = arr[::-1]
print(reverse_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.94731873 0.11772532 0.90689006]
  [0.85752381 0.188866   0.40473293]
  [0.32055926 0.26352241 0.51871936]]

 [[0.63652117 0.36322203 0.64040038]
  [0.36593546 0.84950762 0.40423566]
  [0.53048642 0.02624819 0.42828337]]

 [[0.88175668 0.40007454 0.02021336]
  [0.61639935 0.73583307 0.1670806 ]
  [0.93720588 0.60044588 0.64781992]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
arr = np.random.rand(10, 10)
min_val = np.min(arr)
max_val = np.max(arr)
print(min_val, max_val)

0.0018031881014523021 0.9965754758517136


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
arr = np.random.rand(30)
mean_val = np.mean(arr)
print(mean_val)

0.47700345854949744


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
arr = np.ones((5, 5), dtype=int)
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

arr = np.zeros((5, 5), dtype=int)
arr[1:-1, 1:-1] = 1
print(arr)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
''' python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
'''
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
arr = np.diag([1, 2, 3, 4], k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
import numpy as np
arr = np.unravel_index(99, (6, 7, 8))
print(arr)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
arr = np.array([[0, 1], [1, 0]])
arr = np.tile(arr, (4, 4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
arr = np.random.rand(5, 5)
arr = (arr - np.mean(arr)) / np.std(arr)
print(arr)

[[-0.4543374  -0.18406939  1.24504851  1.22131384  1.22121278]
 [ 0.20415105  1.44373829  0.69827895  1.48190216  1.24744176]
 [-0.65426221 -1.28758642 -1.17561739  0.75606097  0.61099198]
 [-1.49145122 -0.41824086 -1.59202677  0.81712357 -0.54890789]
 [-1.13416455 -0.46016837 -1.11098846  0.3813425  -0.81678544]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
arr = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
print(arr)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
arr = np.dot(np.random.rand(5, 3), np.random.rand(3, 2))
print(arr)

[[1.15221353 1.06411184]
 [0.70625573 0.87685629]
 [1.11972644 1.20860421]
 [0.75992295 0.92735223]
 [0.55492992 0.51889879]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
z = np.array([1, 2, 3])
print(z**z)
print(2 << z >> 2)
#print(z <- z) // illegal command or invalid syntax
print(1j*z)
print(z/1/1)
#print(Z<Z>Z) // illegal command or invalid syntax

[ 1  4 27]
[1 2 4]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
'''np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)'''

import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-2889552415.py:7: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-2889552415.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-2889552415.py:9: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
import numpy as np
arr = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(arr)), arr)) #ceiling is used to round up the floting values and abs means gives absoult value removing negative sign

[ -7.  -5.   5.   6. -10.  -5.  -2.  -4.   4.  -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2))

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

*   List item
*   List item



In [33]:
#arr = np.ones(1) / 0
#print(arr)

import warnings
warnings.filterwarnings('ignore')


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
arr = np.datetime64('today', 'D') - np.timedelta64(0, 'D')
print(arr)

2025-10-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
arr = np.ones(3) * 1
b = np.ones(3) * 2
np.add(arr, b, out=b)
print(b)
np.divide(arr, 2, out=arr)
print(arr)
np.negative(arr, out=arr)

[3. 3. 3.]
[0.5 0.5 0.5]


array([-0.5, -0.5, -0.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
arr = np.random.uniform(0, 10, 10)
print('random array', arr)
print(arr - arr % 1) #gives factorial of elements and substract with original elements
print(np.floor(arr))
print(np.ceil(arr) - 1)
print(arr.astype(int))

random array [0.42712035 5.06002356 2.87923588 6.61261214 7.50244347 8.12918136
 2.9133254  2.72675655 4.89232663 6.30067559]
[0. 5. 2. 6. 7. 8. 2. 2. 4. 6.]
[0. 5. 2. 6. 7. 8. 2. 2. 4. 6.]
[0. 5. 2. 6. 7. 8. 2. 2. 4. 6.]
[0 5 2 6 7 8 2 2 4 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
arr = np.zeros((5, 5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
def generate():
  for x in range(10):
    yield x
arr = np.fromiter(generate(), dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


`[link text](https://)#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)`

In [44]:
arr = np.linspace(0, 1, 11, endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.01375685 0.0172409  0.04404777 0.2522437  0.33171742 0.52961442
 0.77578101 0.84041258 0.88077127 0.91443653]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [47]:
arr = np.arange(10)
np.add.reduce(arr)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [48]:
arr1 = np.random.randint(0, 2, 5)
arr2 = np.random.randint(0, 2, 5)
print(np.allclose(arr1, arr2))

False


#### 43. Make an array immutable (read-only) (★★☆)

> Add blockquote

> Add blockquote





In [54]:

# Create a normal array
arr = np.array([10, 20, 30, 40, 50])
# Make it read-only
arr.flags.writeable = False
print("Array:", arr)
# Try to modify it
#arr[0] = 99   # ❌ This will raise an error


Array: [10 20 30 40 50]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [55]:
arr = np.random.random((10, 2))
x, y = arr[:, 0], arr[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r)

[0.49675245 0.52023818 0.96576764 0.55355138 0.81000846 0.71199154
 0.87760575 0.3616613  0.94053986 0.72031922]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [56]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.17966722 0.41774179 0.87209254 0.28710294 0.69597932 0.77235514
 0.93961004 0.         0.11472561 0.54364626]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [58]:
arr = np.zeros((5, 5), [('x', float), ('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))  #meshgrid means create the coordinates
print(arr)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [59]:
arr1 = np.arange(8)
arr2 = arr1 + 0.5
c = 1.0 / np.subtract.outer(arr1, arr2)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [63]:
arr = np.array([np.int8, np.int16, np.int32, np.int64, np.float32, np.float64])
arr = arr.tolist()
for i in arr:
  if np.issubdtype(i, np.integer):
    print(np.iinfo(i).min)
    print(np.iinfo(i).max)
  elif np.issubdtype(i, np.floating):
    print(np.finfo(i).min)
    print(np.finfo(i).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [68]:
import numpy as np

# Create a large array
large_array = np.arange(100)

# By default, large arrays are truncated
print("Default printing:")
print(large_array)

# To print all elements, change the print options
np.set_printoptions(threshold=np.inf)

print("\nPrinting all elements:")
print(large_array)

# You can reset the print options later if needed
# np.set_printoptions(threshold=1000) # Or your desired default

Default printing:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Printing all elements:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [69]:
arr = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(arr - v)).argmin()
print(arr[index])

91


\#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [75]:
# Define the data type (structure)
dt = np.dtype([
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', float), ('g', float), ('b', float)])
])

# Create structured array
arr = np.array([
    ((0.0, 0.0), (1.0, 0.0, 0.0)),   # Red point
    ((1.0, 1.0), (0.0, 1.0, 0.0)),   # Green point
    ((0.5, 0.2), (0.0, 0.0, 1.0))], dtype=dt) #blue point

print(arr)


[((0. , 0. ), (1., 0., 0.)) ((1. , 1. ), (0., 1., 0.))
 ((0.5, 0.2), (0., 0., 1.))]


[link text](https:// [link text](https://:\))#### 52. Consider a random vector

1.   List item
2.   List item

with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [80]:
arr = np.random.random((10, 2)) # example (100, 2)
x, y = np.atleast_2d(arr[:, 0], arr[:, 1])
d = np.sqrt((x - x.T)**2 + (y - y.T)**2)
arr = d.astype(float)
print(arr)

[[0.         0.19151088 0.71474871 0.54857385 0.21113029 0.62999408
  0.53378252 0.61254213 0.40395836 0.21228217]
 [0.19151088 0.         0.78743977 0.61527783 0.34102855 0.44086484
  0.58914263 0.45999752 0.22588994 0.38619895]
 [0.71474871 0.78743977 0.         0.17216557 0.50844532 1.0149299
  0.20136589 0.80270946 0.81791528 0.5706708 ]
 [0.54857385 0.61527783 0.17216557 0.         0.34812217 0.86154748
  0.04125591 0.66684247 0.6545198  0.42499913]
 [0.21113029 0.34102855 0.50844532 0.34812217 0.         0.72404746
  0.34026372 0.62775955 0.48667437 0.11072855]
 [0.62999408 0.44086484 1.0149299  0.86154748 0.72404746 0.
  0.82292688 0.25712478 0.23756002 0.80132379]
 [0.53378252 0.58914263 0.20136589 0.04125591 0.34026372 0.82292688
  0.         0.62595085 0.61876    0.42524315]
 [0.61254213 0.45999752 0.80270946 0.66684247 0.62775955 0.25712478
  0.62595085 0.         0.24811192 0.72704555]
 [0.40395836 0.22588994 0.81791528 0.6545198  0.48667437 0.23756002
  0.61876    0.248111

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [81]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [86]:
arr = np.genfromtxt("file.txt", delimiter=",", dtype=int, filling_values=-1)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [85]:
%%writefile file.txt
1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11

Writing file.txt


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [87]:
arr = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(arr):
  print(index, value)
print()
for index in np.ndindex(arr.shape):
  print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)